services:
  api-branden:
    image: ghcr.io/uyamaa/api-branden:latest
    build:
      context: .
    container_name: api-branden-container
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEFAULT_USER_ID: ${DEFAULT_USER_ID:-}
      INGEST_API_KEY: ${INGEST_API_KEY:-}
    ports:
      - "8002:8000"
    restart: unless-stopped
